package org.uqbar.less

object Syntax {
	val identifier = "[a-z_A-Z][a-z_A-Z0-9]*"
	val number = "-?[0-9]+"
	val sentenceSep = ","
	val assignOp = "="
	val lineSep = ";"
	val arrayOpen = "#["
	val arrayClose = "]"
	val codeOpen = "{"
	val codeClose = "}"
	val parensOpen = "("
	val parensClose = ")"
	val argOpen = "("
	val argClose = ")"
	val atOpen = "["
	val atClose = "]"
	val andOp = "&&"
	val orOp = "||"
	val eqOp = "=="
	val neqOp = "!="
	val geOp = ">="
	val gtOp = ">"
	val ltOp = "<"
	val leOp = "<="
	val addOp = "+"
	val subOp = "-"
	val mulOp = "*"
	val divOp = "/"
	val notOp = "!"
	val access = "."
	val ifKeyword = "if"
	val whileKeyword = "while"
	val elseKeyword = "else"
	val defKeyword = "def"
	val objectKeyword = "object"
}